### ISSUE TITLE
Wrap title so it doesn't come too close to edges

### ISSUE THREAD

**Issue by billiemead** [thewhyse/knipperstg#11]
[![Screenshot_2023-10-19_17-37-41.png](https://mrkr.io/s/6531696524bf4e04a7d4c77e/2)](https://mrkr.io/s/6531696524bf4e04a7d4c77e/0)

Steps to reproduce:

Actual result:

Expected result:
Knipper 3PL Increase 
Sales for an On-Demand 
Injectable Case Study

---

**Reported by:** Michelle Leung (mleung@proximylhealth.com)

**Source URL:** [https://knipperstg.wpengine.com/resources/case-studies/](https://knipperstg.wpengine.com/resources/case-studies/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6531696524bf4e04a7d4c781_fb3afcb0628a56e3?advanced=1)

**Console:** [📃  0 logs](https://app.marker.io/i/6531696524bf4e04a7d4c781_fb3afcb0628a56e3?advanced=1&activePane=console)

**Network:** [View network logs](https://app.marker.io/i/6531696524bf4e04a7d4c781_fb3afcb0628a56e3?advanced=1&activePane=console)

**Session replay:** [Watch last 30 seconds](https://app.marker.io/i/6531696524bf4e04a7d4c781_fb3afcb0628a56e3?advanced=1&sessionReplay=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 118.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1728 x 1117</td></tr><tr><td><strong>OS</strong></td><td>OS X 13.3.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1728 x 902</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by rayhova** [comment]
padding left and right added

**Comment by billiemead** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6531696524bf4e04a7d4c781_fb3afcb0628a56e3) - This issue was marked as **✅ Resolved** in Marker.io

**Comment by billiemead** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6531696524bf4e04a7d4c781_fb3afcb0628a56e3) - **Michelle Leung** commented via Marker.io:

> Update not showing

[Reply here](https://app.marker.io/i/6531696524bf4e04a7d4c781_fb3afcb0628a56e3)

**Comment by billiemead** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6531696524bf4e04a7d4c781_fb3afcb0628a56e3) - This issue was marked as **❗️ Open** in Marker.io
