### ISSUE TITLE
GLOBAL: Reduce headline size

### ISSUE THREAD

**Issue by billiemead** [thewhyse/knipperstg#28]
[![Screenshot_2023-10-19_17-59-13.png](https://mrkr.io/s/65316e715e2bc3af98841748/2)](https://mrkr.io/s/65316e715e2bc3af98841748/0)

Steps to reproduce:

Actual result:

Expected result:
Reduce font size of the headlines (Marketing & Sample Management, Custom Pharmacy, 3rd Party Logistics) to be the same size as the jump links at the top

---

**Reported by:** Michelle Leung (mleung@proximylhealth.com)

**Source URL:** [https://knipperstg.wpengine.com/resources/case-studies/](https://knipperstg.wpengine.com/resources/case-studies/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/65316e715e2bc3af9884174b_d6526d4969a0b50e?advanced=1)

**Console:** [📃  0 logs](https://app.marker.io/i/65316e715e2bc3af9884174b_d6526d4969a0b50e?advanced=1&activePane=console)

**Network:** [View network logs](https://app.marker.io/i/65316e715e2bc3af9884174b_d6526d4969a0b50e?advanced=1&activePane=console)

**Session replay:** [Watch last 30 seconds](https://app.marker.io/i/65316e715e2bc3af9884174b_d6526d4969a0b50e?advanced=1&sessionReplay=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 118.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1728 x 1117</td></tr><tr><td><strong>OS</strong></td><td>OS X 13.3.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1728 x 902</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by rayhova** [comment]
sized reduced in brochures/videos/case-studies scss pages

**Comment by billiemead** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/65316e715e2bc3af9884174b_d6526d4969a0b50e) - This issue was marked as **✅ Resolved** in Marker.io

**Comment by billiemead** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/65316e715e2bc3af9884174b_d6526d4969a0b50e) - **Michelle Leung** commented via Marker.io:

> Complete

[Reply here](https://app.marker.io/i/65316e715e2bc3af9884174b_d6526d4969a0b50e)
