### ISSUE TITLE
TABLET: Align Headline

### ISSUE THREAD

**Issue by billiemead** [thewhyse/knipperstg#34]
[![Screenshot_2023-10-19_18-08-49.png](https://mrkr.io/s/653170b0ed7cb9b02362d24d/2)](https://mrkr.io/s/653170b0ed7cb9b02362d24d/0)

Steps to reproduce:

Actual result:

Expected result:
Can the headline "Case Studies" move over to the right so it's aligned with the logo and the breadcrumbs?

---

**Reported by:** Michelle Leung (mleung@proximylhealth.com)

**Source URL:** [https://knipperstg.wpengine.com/resources/case-studies/](https://knipperstg.wpengine.com/resources/case-studies/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/653170b0ed7cb9b02362d250_b1182b4b2e1110c6?advanced=1)

**Console:** [📃  0 logs](https://app.marker.io/i/653170b0ed7cb9b02362d250_b1182b4b2e1110c6?advanced=1&activePane=console)

**Network:** [View network logs](https://app.marker.io/i/653170b0ed7cb9b02362d250_b1182b4b2e1110c6?advanced=1&activePane=console)

**Session replay:** [Watch last 30 seconds](https://app.marker.io/i/653170b0ed7cb9b02362d250_b1182b4b2e1110c6?advanced=1&sessionReplay=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 118.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1728 x 1117</td></tr><tr><td><strong>OS</strong></td><td>OS X 13.3.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>798 x 902</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by rayhova** [comment]
adjusted in brochures/case-studies/videos scss

**Comment by billiemead** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/653170b0ed7cb9b02362d250_b1182b4b2e1110c6) - This issue was marked as **✅ Resolved** in Marker.io

**Comment by billiemead** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/653170b0ed7cb9b02362d250_b1182b4b2e1110c6) - **Michelle Leung** commented via Marker.io:

> Headline and breadcrumbs are aligned, but they should line up with the logo.

[Reply here](https://app.marker.io/i/653170b0ed7cb9b02362d250_b1182b4b2e1110c6)

**Comment by billiemead** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/653170b0ed7cb9b02362d250_b1182b4b2e1110c6) - This issue was marked as **✅ Resolved** in Marker.io

**Comment by billiemead** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/653170b0ed7cb9b02362d250_b1182b4b2e1110c6) - **Michelle Leung** commented via Marker.io:

> Complete

[Reply here](https://app.marker.io/i/653170b0ed7cb9b02362d250_b1182b4b2e1110c6)
