### ISSUE TITLE
GLOBAL: Adjust Video Sizes and Display

### ISSUE THREAD

**Issue by billiemead** [thewhyse/knipperstg#42]
[![Screenshot_2023-10-19_19-30-15.png](https://mrkr.io/s/653183c7896b9b3785b9fe49/2)](https://mrkr.io/s/653183c7896b9b3785b9fe49/0)

Steps to reproduce:

Actual result:

Expected result:
Keep the videos the same size as desktop, but stack them on top of each other to create 1 column. 

Reduce the amount of white in the card

---

**Reported by:** Michelle Leung (mleung@proximylhealth.com)

**Source URL:** [https://knipperstg.wpengine.com/resources/videos/](https://knipperstg.wpengine.com/resources/videos/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/653183c7896b9b3785b9fe4c_9717262904e5f00d?advanced=1)

**Console:** [📃  0 logs](https://app.marker.io/i/653183c7896b9b3785b9fe4c_9717262904e5f00d?advanced=1&activePane=console)

**Network:** [View network logs](https://app.marker.io/i/653183c7896b9b3785b9fe4c_9717262904e5f00d?advanced=1&activePane=console)

**Session replay:** [Watch last 30 seconds](https://app.marker.io/i/653183c7896b9b3785b9fe4c_9717262904e5f00d?advanced=1&sessionReplay=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 118.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1728 x 1117</td></tr><tr><td><strong>OS</strong></td><td>OS X 13.3.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>925 x 902</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by billiemead** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/653183c7896b9b3785b9fe4c_9717262904e5f00d) - **Michelle Leung** commented via Marker.io:

> This applies to Tablet and Mobile

[Reply here](https://app.marker.io/i/653183c7896b9b3785b9fe4c_9717262904e5f00d)

**Comment by rayhova** [comment]
adjusted in videos.scss

**Comment by billiemead** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/653183c7896b9b3785b9fe4c_9717262904e5f00d) - This issue was marked as **✅ Resolved** in Marker.io

**Comment by billiemead** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/653183c7896b9b3785b9fe4c_9717262904e5f00d) - **Michelle Leung** commented via Marker.io:

> Complete

[Reply here](https://app.marker.io/i/653183c7896b9b3785b9fe4c_9717262904e5f00d)
