### ISSUE TITLE
GLOBAL: CTA Font Size

### ISSUE THREAD

**Issue by billiemead** [thewhyse/knipperstg#51]
[![Screenshot_2023-10-19_19-48-13.png](https://mrkr.io/s/653187fd8d6be7d51568c728/2)](https://mrkr.io/s/653187fd8d6be7d51568c728/0)

Steps to reproduce:

Actual result:

Expected result:
For all CTAs, can you confirm if the font size in the buttons is the same as the homepage? It looks larger?

---

**Reported by:** Michelle Leung (mleung@proximylhealth.com)

**Source URL:** [https://knipperstg.wpengine.com/resources/brochures/](https://knipperstg.wpengine.com/resources/brochures/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/653187fd8d6be7d51568c72b_4498c3ec0ab5c9c3?advanced=1)

**Console:** [📃  0 logs](https://app.marker.io/i/653187fd8d6be7d51568c72b_4498c3ec0ab5c9c3?advanced=1&activePane=console)

**Network:** [View network logs](https://app.marker.io/i/653187fd8d6be7d51568c72b_4498c3ec0ab5c9c3?advanced=1&activePane=console)

**Session replay:** [Watch last 30 seconds](https://app.marker.io/i/653187fd8d6be7d51568c72b_4498c3ec0ab5c9c3?advanced=1&sessionReplay=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 118.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1728 x 1117</td></tr><tr><td><strong>OS</strong></td><td>OS X 13.3.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1723 x 902</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by rayhova** [comment]
Font-size for both are 22px
font-weight is 700 for both. They are the same

**Comment by billiemead** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/653187fd8d6be7d51568c72b_4498c3ec0ab5c9c3) - This issue was marked as **✅ Resolved** in Marker.io

**Comment by billiemead** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/653187fd8d6be7d51568c72b_4498c3ec0ab5c9c3) - **Michelle Leung** commented via Marker.io:

> The font size still looks larger than the homepage font buttons.

[Reply here](https://app.marker.io/i/653187fd8d6be7d51568c72b_4498c3ec0ab5c9c3)

—
**Attachments:**

- [CTA Button Font Size.png](https://files.marker.io/f/64f6ba45dff008ff0b0eb49b/653698fe896b9b3785cdcd17) (*2.8MB*)

**Comment by billiemead** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/653187fd8d6be7d51568c72b_4498c3ec0ab5c9c3) - **Michelle Leung** commented via Marker.io:

> Complete

[Reply here](https://app.marker.io/i/653187fd8d6be7d51568c72b_4498c3ec0ab5c9c3)
