### ISSUE TITLE
Global: drop-down buttons don't work for me when I resize window to tablet view

### ISSUE THREAD

**Issue by billiemead** [thewhyse/knipperstg#69]
[![Screenshot_2023-10-19_21-03-54.png](https://mrkr.io/s/653199ba896b9b3785ba9cc6/2)](https://mrkr.io/s/653199ba896b9b3785ba9cc6/0)

Steps to reproduce:

Actual result:

Expected result:

---

**Reported by:** Tessa White (twhite@proximylhealth.com)

**Source URL:** [https://knipperstg.wpengine.com/resources/videos/](https://knipperstg.wpengine.com/resources/videos/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/653199ba896b9b3785ba9cc9_23bafae8d932b187?advanced=1)

**Console:** [📃  0 logs](https://app.marker.io/i/653199ba896b9b3785ba9cc9_23bafae8d932b187?advanced=1&activePane=console)

**Network:** [View network logs](https://app.marker.io/i/653199ba896b9b3785ba9cc9_23bafae8d932b187?advanced=1&activePane=console)

**Session replay:** [Watch last 30 seconds](https://app.marker.io/i/653199ba896b9b3785ba9cc9_23bafae8d932b187?advanced=1&sessionReplay=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 117.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 13.5.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>751 x 1385</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.7999999523162842x</td></tr></table>

**Comment by billiemead** [comment]
Need to update script so it works on resize as the menus do. i think if you remove it from the page code block and enqueue it in the child theme function file it'll work. lmk if you want to discuss more.

**Comment by rayhova** [comment]
The issue was that the jquery script was set to load on document ready. (dragging a window to resize is not a real-life end user scenario). I added a "window resize" function. 

I also removed the scripts from the divi page and added to the knipper.js file.

**Comment by billiemead** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/653199ba896b9b3785ba9cc9_23bafae8d932b187) - This issue was marked as **✅ Resolved** in Marker.io

**Comment by billiemead** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/653199ba896b9b3785ba9cc9_23bafae8d932b187) - **Michelle Leung** commented via Marker.io:

> Drop downs are only for mobile
> 
> Complete

[Reply here](https://app.marker.io/i/653199ba896b9b3785ba9cc9_23bafae8d932b187)
