### ISSUE TITLE
Video Cards overlapping

### ISSUE THREAD

**Issue by billiemead** [thewhyse/knipperstg#72]
[![Screenshot_2023-10-19_21-35-24.png](https://mrkr.io/s/6531a11c5572155c7d8cb226/2)](https://mrkr.io/s/6531a11c5572155c7d8cb226/0)

I saw there was another comment about adjusting the size of the cards, but didn't see a screenshot showing the overlap. 

---

**Reported by:** Melissa Hindle (mhindle@mjhlifesciences.com)

**Source URL:** [https://knipperstg.wpengine.com/resources/videos/](https://knipperstg.wpengine.com/resources/videos/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6531a11c5572155c7d8cb229_927bb1b825e98a4d?advanced=1)

**Console:** [📃  0 logs](https://app.marker.io/i/6531a11c5572155c7d8cb229_927bb1b825e98a4d?advanced=1&activePane=console)

**Network:** [View network logs](https://app.marker.io/i/6531a11c5572155c7d8cb229_927bb1b825e98a4d?advanced=1&activePane=console)

**Session replay:** [Watch last 30 seconds](https://app.marker.io/i/6531a11c5572155c7d8cb229_927bb1b825e98a4d?advanced=1&sessionReplay=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 118.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1280 x 720</td></tr><tr><td><strong>OS</strong></td><td>Windows 11 (15.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1280 x 563</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1.5x</td></tr></table>

**Comment by rayhova** [comment]
added media query for 1280 breakpoint

**Comment by billiemead** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6531a11c5572155c7d8cb229_927bb1b825e98a4d) - This issue was marked as **✅ Resolved** in Marker.io

**Comment by billiemead** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/6531a11c5572155c7d8cb229_927bb1b825e98a4d) - **Michelle Leung** commented via Marker.io:

> Complete

[Reply here](https://app.marker.io/i/6531a11c5572155c7d8cb229_927bb1b825e98a4d)
